language: python
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

stages:
  - name: linting
  - name: test
  - name: deploy
    if: tag IS present

env:
  global:
  - VERSION="10.0" TESTS="1" LINT_CHECK="0" MAKEPOT="0" ODOO_REPO="odoo/odoo"

jobs:
  include:
    # TODO: move to GH actions
    - stage: linting
      python: 3.8
      install: pip install pre-commit twine
      script:
        - pip wheel -w /tmp/build --no-deps .
        - twine check /tmp/build/*
      env: TESTS="0"
    - stage: test
      python: 2.7
      env: VERSION="10.0"
    - stage: test
      python: 3.5
      env: VERSION="11.0"
    - stage: test
      python: 3.5
      env: VERSION="12.0"
    - stage: test
      python: 3.6
      env: VERSION="12.0"
    - stage: test
      python: 3.7
      env: VERSION="12.0"
    - stage: test
      python: 3.6
      env: VERSION="13.0"
    - stage: test
      python: 3.7
      env: VERSION="13.0"
    - stage: test
      python: 3.6
      env: VERSION="14.0"
    - stage: test
      python: 3.7
      env: VERSION="14.0"
    - stage: test
      python: 3.8
      env: VERSION="15.0"
    - stage: test
      python: 3.8
      env: VERSION="16.0"
    - stage: test
      python: 3.6
      env: VERSION="master"
  # TODO: test 3.8
  allow_failures:
    - python: 3.8-dev
    - env: VERSION="master"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install -e .
  - mv tests/test_helper test_helper

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
